# Generated by Django 4.0.2 on 2022-02-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=10)),
                ('subject_text', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=10)),
                ('system_name', models.CharField(max_length=10)),
            ],
        ),
    ]
