# Generated by Django 4.0.2 on 2022-02-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='show_flag',
            field=models.BooleanField(default=True),
        ),
    ]
