# Generated by Django 3.2.11 on 2022-02-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220207_0636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainTest',
        ),
    ]
